### ISSUE TITLE
Using a relative path to the json file seems to invoke an error

### ISSUE THREAD

**Issue by jgweir** [usharesoft/hammr#20] opened 2015-04-23 15:41 UTC
Using the following example, invokes an error in hammr:

```
hammr template create --file ./base-template.json
error downloading ./base-template.json: local file url may start with / or file:. Unknown url of type: ./base-template.json
```

**Comment by obourdon** [comment] 2015-08-31 13:38
This seems to be fixed

**Comment by jbremond** [comment] 2015-12-15 12:42
I have reproduced the issue with hammr 0.2.5.8

**Comment by jbremond** [comment] 2016-04-14 14:14
For the master, this code is now in another project: https://github.com/usharesoft/ussclicore

The fix as been back-port there.

I close the issue

**Closed by jbremond** 2016-04-14 14:14 UTC
Labels: bug
