### ISSUE TITLE
builder for Google Compute Engine fails

### ISSUE THREAD

**Issue by alefebvr** [usharesoft/hammr#408] opened 2018-06-06 13:34 UTC
When trying to build a template with the builder below, the following error is displayed:
```
hammr> template build --file template2.yml
INFO: You provided a yaml file, checking...
Generating 'Google Compute Engine' image (1/1)
ERROR: Builder type unknown: Google Compute Engine
```
I managed to fix the issue by:
- replacing def generate_gce with def generate_google in file hammr/utils/generate_utils.py
- replacing "Google Compute Engine" with "google" in the first type occurrence in the template yaml file.

```
builders:
- type: "Google Compute Engine" 
  account:
    type: "Google Compute Engine"
    name: My GCE Account
    username: my@email.com
    certPassword: XXXXXXX
    cert: "/my/certificate/gce.p12"
  computeZone: europe-west1-a
  bucketLocation: EU
  bucket: mybucket
  projectId: my-project
  storageClass: STANDARD
  diskNamePrefix: uss-
  description: CentOS Core machine image
```

**Comment by alefebvr** [comment] 2018-06-06 13:38
Note that the hammr documentation will have to be updated accordingly too
See the example on http://docs.usharesoft.com/projects/hammr/en/latest/pages/machine-images/builders/builders-gce.html

**Comment by AliceAlbano** [comment] 2018-07-09 13:55
Thank you for logging the issue. I was able to reproduce the bug, but for the fix, I only need to update generate_gce by generate_google. The builder type "Google Compute Engine" works for me, so I think the documentation does not need to be updated.

**Comment by AliceAlbano** [comment] 2018-07-11 06:30
Fixed by #429

**Closed by AliceAlbano** 2018-07-11 06:30 UTC
Labels: bug
